<?php $thisPage="Day 2 of Tic Tac Toe"; ?>
<?php $title="Day 2 of Tic Tac Toe"; ?>
<?php include("../topsubfolder.php"); ?>
	<div class="center">
		<h3>Day 2 of Tic Tac Toe</h3>
	</div>
	<p>At this point, I think I have to disregard most of what I wrote in Day 1.  The realization that most of what I thought was wrong came in the afternoon, after a fellow student shared his working version of Tic Tac Toe and its code.  I was way off in terms of how this project will appear in terms of how many pages it will exist and how it record/reflect moves made on the board.  The game can exist on a screen without clicking links; it involves using/referencing query string parameters.  For now, I really feel out of my league.  I have used query string params in code only once up until now, and in that code it was just one instance.  My rock/paper/scissors game used $_GET to get the input of the user's choice of rock or paper or scissors.  That data received from the query string parameter was compared with the choice made by the computer.  In this case, the choice entered in the input field was converted to a string, and the string compared to the computer's string.  From there, a value was spit out.  Now, in this case, I have to use query string parameters to record the state of the board.  I see how the other student did so, with a series of numbers to reflect each player's choice.  But really, I don't know how I'll use that usefully to get to the next page, where the most up-to-date state of the board is reflected visually.  I'm just at a loss on how to do so.</p>

	<p>It's one thing to try to get a simple input and then spit out a result.  But it's another thing to take a click on the page and then reflect that input back on the field with giving another choice.  As of right now, I don't even know how to make a link on a page into a query string parameter.  I can make links go to other pages, but to make the link go to the same page and then reflect a different state of possible links to click that will update the query string parameter that will send it to the next page to reflect the newer state of the board, and so on until a victory is achieved, well, jeez, I just don't know if I have the ability to do so.  I can imagine using the query string params initially, as each link will reference a unique query for that board at the time.  There are nine possible choices.  I can even see how that would enter a string, and how that could perhaps update the board.  But now, I'm at a loss.  Would I have to make 9 choices, and for each choice, have a unique resulting query string that would show the board for that choice, and then there would be 8 choices that would result?  In that case, I could see that for each choice, I'd have to write code to reflect the possible choice.  That would mean nine possibilities having each 8 results, and each 8 result having 7 possible results, etc.  I calculated what 9! (the factorial of 9) would be, and got 362,880.  Of course, there are not that many possible combinations.  If you win before all 9 choices are made (you win quickly, in other words), I wouldn't have to continue to enumerate the possible resulting strings.  But, even still, it would just be a massive undertaking.  That can't work.</p>

	<p>  That being said, the other student definitely did not resort to such efforts.  Heck, it was rather quick in the end.  He didn't even write out any full possible configurations of the string.  But what he did do is something that I feel is beyond me-- giving what I'd call dynamic changes to the query string such that there is code telling how to change the query string param, which would result in the future board.  There are 8 possible arrangements of 3 Xs or Os in a row.  You just really need to watch out for those possible configurations.  But, as of now, I really don't think I have the ability to write out the directions for editing the query string parameters.  Like I said earlier, I don't even know how to use the links to update the query string params in such a way as to just update the page you are on (visually).  I just feel like I'm unable to complete this exercise.  It's really hard to get even a few steps as of now.</p>
	</div>
	</body>
</html>