<?php $thisPage="on_coding"; ?>
<?php $title="On Coding"; ?>
<?php include("../topsubfolder.php"); ?>
	<div class="center">
	<img src="twain.jpg" alt="Twain Frustrated" style="width:384px;height:512px;">
		<h3>On Coding</h3>
	</div>
	<p>Reflecting on my coding experiences so far in this crash course at OCS elicits a wide range of thoughts.  These past few months, from my acceptance into the program, to the beginning exercises outside the classroom to prepare me, to these past few weeks taking my first steps into programming and design, have been a roller coaster of ups and downs, of exciting moments and overwhelming frustration.  Overall, I'm very pleased with what I've learned so far, but if I'm honest, I have to spend some time talking about the frustrations that I've been through, as well. In this post, I'll probably bounce back and forth a bit between both extremes, the goods and bads.  I hope it'll be a coherent account of my time so far.</p>
	<p>First off, I really love that I get excited by writing functions.  Who knew that'd be a thing?  I know I've repeated this ad nauseum in both my biography and in conversation, but I think one thing that draws me to coding is that it shares some overall functional similarities with symbolic logic.  Having previous experience in both working through symbolic logic problems in grad school courses I took, as well as in teaching logic to students, I have just really enjoyed working from assumptions and premises through arguments using the argumentative structural framework of logic to reach the conclusion that you know is there, is true.  Writing a function is so similar!  You know what the conclusion is supposed to be. You have your assumptions, your basic elements, and you have to use a framework of methods and tools supplied by the language and its rules.  It's very satisfying when you finally test or run your code and it works! It's a feeling of elation for me.  So often it doesn't work until I try and try, or get help, so when it finally comes together, I just feel such a rush.  I hope that feeling doesn't go away.  I'm afraid that I have this level of excitement only because this thing I'm learning is so new that the newness itself is what feeds the excitement.  I mean, I bet the guides that lead groups down the Grand Canyon just were so excited by their jobs, and would be just floored by the beauty of the canyon as they lead their first groups down the trail.  Two years later, do they still feel that same excitement when their alarm wakes them to go to work?  Will programming and coding still give me that rush when I do it right?</p>
	<p>I think that part of my worry here is that I don't know what a job in coding is like.  I try to ask those visitors and speakers we get around here, just to hear what they think.  But asking about someone's job is usually the worst type of question.  And really, how well can one sum up their work life in just a few sentences?  It's a complicated conversation, and thus I really can't expect a good answer that could give me an idea of what I should expect in the coming months when I finally set out on my own career path in the field (the coding gods willing, that is).  Still, I have reservations, and I think they mostly stem from just a lack of awareness of what to expect.  Yet, I know that this feeling would be there no matter where I'd be right now.  Leaving a future in academic philosophy, I should know well that a lack of knowledge of the future shouldn't be a bad thing always.  I found out that I didn't want to go through all the hoops it took to succeed at a research university teaching philosophy.  That I didn't want that awful short term career path just for the hope of a good job coming around.  So why should I be so unwilling to trust this doubt I experience when I reflect about how little I really know about coding?  I need to give it more of a chance.</p>
	<p>I also think that what feeds into my worry about the future is that I still feel like I'm not good at this.  I have to ask so many questions.  I can't think of a project that I've done so far that wasn't aided by the instructors and aides.  I just don't feel confident in my abilities.  When I present my code, either for show or when I'm looking for help, often there are simple errors that I'm missing, stuff I shouldn't be missing.  Or, conversely, there are huge problems with the structure of my program or functions that show I'm not really getting what I'm being asked to do.  If I can't get over some of these issues in the next five weeks, really, what can I offer an employer?  I don't want to get hired only to tell them that they have to hold my hand for the next few months while I catch up.  And, since I know someone might be reading this, I totally know that this is mostly in my head, or that what I'm feeling here might be something like imposter syndrome, or something along those lines.  I know that this is something I should set aside for now.  For the purposes of this article, however, I'm just explaining what I think about my coding, and it's not a defense or justification of the validity of those feelings.</p>
	<p>I don't want to end on a bad note.  I really don't want to give the impression that I'm doom and gloom about either my current progress or the future of my coding.  Overall, I think that what I wrote above in part is just a reflection of how I tend to think-- too critically of myself, too easy to fall into doubt.  I want to reiterate, I really get excited about this stuff.  I think it's so cool what it means to code--to use the rules and structure of a language, combined with functions, variables, and a lot of coordination and combination of elements of the program to <i>do</i> things. It's so great to see us create things (even crude facsimiles of things) that, well, I see and interact with every day.  Websites, apps, machines that perform actions.  It all runs because of stuff of the kind we do here at OCS.  It's pretty amazing to see what goes in to the design, the critical thinking that goes into creating programs.  I really hope that as I learn more, what I've experienced so far about coding-- the amount of critical thinking and just mental gear-grinding that goes into the conceptualization of what I'm trying to accomplish-- remains.  The mental energy expended, the amount of mental computing that goes into this, is what I enjoy the most.  And I want to continue to have to think this hard, to really just push my mind towards accomplishing the expected goals.  I want to continue to experience this mental pressure, this work.  It's so much better, more fulfilling, than so much else I could be doing were it not for the chance to study here at OCS.</p>
	</div> 
	</body>
</html>